services:
  postgres: 
    image: postgres:16
    container_name: msasca-postgres
    environment:
      POSTGRES_DB: msasca
      POSTGRES_USER: msasca
      POSTGRES_PASSWORD: msasca
    ports:
      - "5432:5432"
    volumes:
      - msasca_pg:/var/lib/postgresql/data

volumes:
  msasca_pg:
