spring:
  config:
    import: "classpath:application-common.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/msasca
    username: msasca
    password: msasca
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never
logging:
  level:
    org.springframework.boot.context.config: DEBUG
sca:
  build:
    images:
      default-image: maven:3.9-eclipse-temurin-17
      rules:
        - build-tool: MAVEN
          jdk-version: "*"
          image: maven:3.9-eclipse-temurin-17
        - build-tool: GRADLE
          jdk-version: "*"
          image: gradle:8.7-jdk17
    workspace:
      base-path: C:/Users/beom/Desktop/buaa-msasca/.workspace