spring:
  config:
    import: "classpath:application-common.yml"
logging:
  level:
    org.springframework.boot.context.config: DEBUG
sca:
  build:
    images:
      default-image: maven:3.9-eclipse-temurin-17
      rules:
        - build-tool: MAVEN
          jdk-version: "*"
          image: maven:3.9-eclipse-temurin-17
        - build-tool: GRADLE
          jdk-version: "*"
          image: gradle:8.7-jdk17