spring:
  config:
    import: "classpath:application-common.yml"
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

server:
  port: 8080

sca:
  workspace:
    base-dir: "C:/msasca"
  storage:
    base-dir: "C:/msasca/storage"
